<?php
/**
 * Created by PhpStorm.
 * User: xin
 * Date: 16/11/21
 * Time: 上午10:37
 */
use PHPUnit\Framework\TestCase;
use app\models\Order;
class MyTest extends TestCase{

//    public function testAdd($a, $b, $expected)
//    {
//        $this->assertEquals($expected, $a + $b);
//    }

//    public function additionProvider()
//    {
//        return [
//            'adding zeros'  => [0, 0, 0],
//            'zero plus one' => [0, 1, 1],
//            'one plus zero' => [1, 0, 1],
//            'one plus one'  => [1, 1, 3]
//        ];
//    }

    protected $order;
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->order = Order::find()->asArray()->one();
    }

    public function testOrder(){
        var_dump(count($this->order));
        $this->assertEquals(20, count($this->order));
    }

    public function testMockOrder(){
//        $order = $this->createMock(Order::class);
//        $order->method('getTypeText')->willReturn('3');
//        $this->assertEquals(3,$order->getTypeText());

        $order = $this->getMockBuilder(Order::class)
            ->enableOriginalConstructor()
            ->getMock();
    }
}