<?php
/**
 * Created by PhpStorm.
 * User: xin
 * Date: 16/11/8
 * Time: 下午6:17
 */

use yii\web\AssetBundle;
class UploadAsset extends AssetBundle{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath = dirname(__FILE__).DIRECTORY_SEPARATOR.'assets';
    }

    public $depends = [
        'app\asset\DropzoneAsset'
    ];
}