<?php
/**
 * Created by PhpStorm.
 * User: xin
 * Date: 16/11/15
 * Time: 下午3:57
 */

namespace app\models;
use yii\base\Action;
use Yii;
use yii\web\UploadedFile;
use app\models\UploadModel;

class DropzoneAction extends Action
{
    public $filePath = '@runtime/image';
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(!file_exists(Yii::getAlias($this->filePath))){
            mkdir(Yii::getAlias($this->filePath));
        }
    }

    public function run(){
        $fileName = 'file';
        $uploadPath = '@runtime/image';
        error_log(var_export(1,true),3,'/tmp/error.log');
        error_log(var_export($_FILES,true),3,'/tmp/error.log');
        if (isset($_FILES[$fileName])) {
            $file = UploadedFile::getInstanceByName($fileName);


            if ($file->saveAs($uploadPath . '/' . $file->name)) {
                //Now save file data to database

                echo 'success';
            }
        }else{
            echo 'false';
        }
    }
}