<?php
/**
 * Created by PhpStorm.
 * User: xin
 * Date: 16/11/15
 * Time: 下午3:57
 */

namespace app\models;
use yii\base\Action;
use Yii;
use yii\web\UploadedFile;
use app\models\UploadModel;

class DropzoneAction extends Action
{
    public $filePath = '@runtime/image';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(!file_exists(Yii::getAlias($this->filePath))){
            mkdir(Yii::getAlias($this->filePath));
        }
    }

    public function run(){
        $model = new UploadModel();

        if (Yii::$app->request->isPost) {
            $model->files = UploadedFile::getInstance($model, 'files');
            if ($model->upload()) {
                // 文件上传成功
                echo "成功";
                return;
            }
        }
    }
}