<?php
/**
 * Created by PhpStorm.
 * User: xin
 * Date: 16/11/15
 * Time: 下午3:38
 */

namespace app\models;

use yii\base\Widget;
class DropzoneWidget extends Widget
{
    public $params;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('dropzone',[
            'model'=>$this->params
        ]);
    }

    public function getViewPath()
    {
        return '@app/views/site';
    }
}